# Generated by Django 5.1.6 on 2025-02-22 09:50
from django.db import migrations

def add_sample_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')  # Django のユーザーモデル
    Transaction = apps.get_model('main', 'Transaction')

    # 適当なユーザーを取得（いなければ作成）
    user = User.objects.first()
    if not user:
        user = User.objects.create(username="testuser", password="testpassword")

    # サンプルデータを追加
    Transaction.objects.create(user=user, amount=1000, description="ランチ代", date="2024-02-22")
    Transaction.objects.create(user=user, amount=-5000, description="家賃", date="2024-02-01")
    Transaction.objects.create(user=user, amount=20000, description="バイト代", date="2024-02-15")

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),  # 直前のマイグレーションを指定
    ]

    operations = [
        migrations.RunPython(add_sample_data),
    ]
